version: '{build}'
image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

nuget:
  disable_publish_on_pr: true

before_build:
  - cmd: dotnet restore

after_build:
- dotnet pack -c Release -o Artifacts

artifacts:
- path: Artifacts\*.nupkg

deploy:
  - provider: Environment
    name: nuget.org
    on:
      branch: master
